# Configuration reference at
# https://docs.gitlab.com/runner/configuration/advanced-configuration.html

gitlab_runner__configuration:
  concurrent: 8
  runners:
    - name: "{{ ansible_hostname + '-docker-group' }}"
      url: https://gitlab.com/
      # Could be a group-token
      _registration_token: "{{ services.gitlab.registration_token }}"
      # Parameter prefixed by _ are not actual toml runner parameters,
      # but are passed during registration of this specific runner.
      # See ansible-doc gitlab_runner a list.
      _tag_list: [docker, managed-by-debops]
      _run_untagged: True
      # This is only supported by a custom version of gitlab-runner
      # (which otherwise does not support gitlab.com)
      _project: "{{ gitlab_runner__gitlab_project }}"
      # "token" attribute will be substituted during registration
      token: no
      ## Only for custom GitLab instances
      # - tls-ca-file
      # - tls-cert-file (example: /etc/ssl/certs/gitlab-runner.crt)
      # - tls-key-file (example: /etc/ssl/private/gitlab-runner.key)
      ## tls-key-file depends on the following two variables being defined:
      # - _ssl_authority_common_name
      # - _ssl_common_name
      executor: docker
      docker:
        image: debian
        privileged: false
        disable_cache: no
        cap_drop: [NET_ADMIN, SYS_ADMIN, DAC_OVERRIDE]
      cache:
        Type: s3
        Shared: true
        s3:
          ServerAddress: s3.amazonaws.com
          AccessKey: "{{ services.amazon['gitlab-runner'].key_id }}"
          SecretKey: "{{ services.amazon['gitlab-runner'].key_secret }}"
          BucketName: "{{ gitlab_runner__cache_bucket_name }}"
          BucketLocation: eu-central-1
          Insecure: false
